version: '3'

services:

    app:
        container_name: flask_view_demo_app
        build:
            context: .
            dockerfile: Dockerfile-app
        restart: always
        environment:
            FLASK_ENV: development
        ports:
            - 5000:5000
        volumes:
            - .:/opt/app
        depends_on:
            - postgresql

    postgresql:
        container_name: flask_view_demo_pg
        image: postgres:10
        restart: always
        environment:
            POSTGRES_DB: flask-view-demo
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        ports:
            - 5432:5432
        volumes:
            - pg-data:/var/lib/postgresql/data


volumes:
    app:
        driver: local
    pg-data:
        driver: local
